--<ScriptOptions statementTerminator=";"/>

ALTER TABLE PACKAGE DROP PRIMARY KEY;

ALTER TABLE CALENDAR DROP PRIMARY KEY;

ALTER TABLE GROUPOFKIDS DROP PRIMARY KEY;

ALTER TABLE KID DROP PRIMARY KEY;

ALTER TABLE FeeMgmt DROP PRIMARY KEY;

ALTER TABLE ATTENDANCE DROP PRIMARY KEY;

ALTER TABLE AGEGROUP DROP PRIMARY KEY;

ALTER TABLE PAYMENT DROP PRIMARY KEY;

ALTER TABLE FEE DROP PRIMARY KEY;

ALTER TABLE CALENDAR DROP INDEX fk_CALENDAR_GROUP1_idx;

ALTER TABLE ATTENDANCE DROP INDEX unique_key_group;

ALTER TABLE ATTENDANCE DROP INDEX unique_key_group;

ALTER TABLE KID DROP INDEX fk_KID_GROUP1_idx;

ALTER TABLE FeeMgmt DROP INDEX kidID_DATE;

ALTER TABLE PACKAGE DROP INDEX fk_PACKAGE_FEE1_idx;

ALTER TABLE KID DROP INDEX fk_KID_PACKAGE1_idx;

ALTER TABLE ATTENDANCE DROP INDEX unique_key_group;

ALTER TABLE PACKAGE DROP INDEX fk_PACKAGE_AGEGROUP_idx;

ALTER TABLE PAYMENT DROP INDEX fk_PAYMENT_KID1_idx;

ALTER TABLE FeeMgmt DROP INDEX kidID_DATE;

DROP TABLE AGEGROUP;

DROP TABLE ATTENDANCE;

DROP TABLE PAYMENT;

DROP TABLE KID;

DROP TABLE CALENDAR;

DROP TABLE FeeMgmt;

DROP TABLE GROUPOFKIDS;

DROP TABLE PACKAGE;

DROP TABLE FEE;

CREATE TABLE AGEGROUP (
	AgeGroupID INT NOT NULL,
	Description VARCHAR(45),
	PRIMARY KEY (AgeGroupID)
) ENGINE=InnoDB;

CREATE TABLE ATTENDANCE (
	AttendanceID INT NOT NULL,
	PresentAbsent VARCHAR(5),
	KID_KidID INT NOT NULL,
	GROUPOFKIDS_GroupID INT NOT NULL,
	DateOfAttendance DATE NOT NULL,
	PRIMARY KEY (AttendanceID)
) ENGINE=InnoDB;

CREATE TABLE PAYMENT (
	PaymentID INT NOT NULL,
	DateLastPaid DATETIME,
	DueDate DATETIME,
	KID_KidID INT NOT NULL,
	PRIMARY KEY (PaymentID)
) ENGINE=InnoDB;

CREATE TABLE KID (
	KidID INT NOT NULL,
	KidName VARCHAR(45),
	PACKAGE_PackageID INT NOT NULL,
	GROUPOFKIDS_GroupID INT NOT NULL,
	PRIMARY KEY (KidID)
) ENGINE=InnoDB;

CREATE TABLE CALENDAR (
	CalendarID INT NOT NULL,
	Date DATE,
	Time VARCHAR(5),
	GROUPOFKIDS_GroupID INT NOT NULL,
	PRIMARY KEY (CalendarID)
) ENGINE=InnoDB;

CREATE TABLE FeeMgmt (
	FeeMgmtID INT NOT NULL,
	FeeID INT NOT NULL,
	KidID INT NOT NULL,
	FeePaid VARCHAR(1) NOT NULL,
	DateOfAttendance DATE NOT NULL,
	Present VARCHAR(1) NOT NULL,
	PRIMARY KEY (FeeMgmtID)
) ENGINE=InnoDB;

CREATE TABLE GROUPOFKIDS (
	GroupID INT NOT NULL,
	GroupName VARCHAR(45),
	PRIMARY KEY (GroupID)
) ENGINE=InnoDB;

CREATE TABLE PACKAGE (
	PackageID INT NOT NULL,
	NumOfClasses INT,
	AGEGROUP_AgeGroupID INT NOT NULL,
	FEE_FeeID INT NOT NULL,
	PackageName VARCHAR(45),
	PRIMARY KEY (PackageID)
) ENGINE=InnoDB;

CREATE TABLE FEE (
	FeeID INT NOT NULL,
	FeeAmount VARCHAR(45),
	PRIMARY KEY (FeeID)
) ENGINE=InnoDB;



CREATE INDEX fk_CALENDAR_GROUP1_idx ON CALENDAR (GROUPOFKIDS_GroupID ASC);

CREATE UNIQUE INDEX unique_key_group ON ATTENDANCE (GROUPOFKIDS_GroupID ASC);

CREATE UNIQUE INDEX unique_key_group ON ATTENDANCE (KID_KidID ASC);

CREATE INDEX fk_KID_GROUP1_idx ON KID (GROUPOFKIDS_GroupID ASC);

CREATE UNIQUE INDEX kidID_DATE ON FeeMgmt (DateOfAttendance ASC);

CREATE INDEX fk_PACKAGE_FEE1_idx ON PACKAGE (FEE_FeeID ASC);

CREATE INDEX fk_KID_PACKAGE1_idx ON KID (PACKAGE_PackageID ASC);

CREATE UNIQUE INDEX unique_key_group ON ATTENDANCE (DateOfAttendance ASC);

CREATE INDEX fk_PACKAGE_AGEGROUP_idx ON PACKAGE (AGEGROUP_AgeGroupID ASC);

CREATE INDEX fk_PAYMENT_KID1_idx ON PAYMENT (KID_KidID ASC);

CREATE UNIQUE INDEX kidID_DATE ON FeeMgmt (KidID ASC);

